### PR TITLE
Fix for status bar banner on non-notch iPhones on iOS 13

### LINKED ISSUE #240: iOS 13: banner shown bellow Status Bar
Hi,
Thanks for this awesome library!

Probably you encounter this bug already, but I couldn’t find an open issue regarding it

Starting from iOS 13, there’s a problem where the banner shows itself beneath the Status Bar

Is there a way to solve it?

Thanks a lot!

### PR DESCRIPTION
**Pull request by igorkulman**
Fixes #240

### CODE REVIEW

**Comment by Daltron** [comment]
EXCELLENT! 😄 Can you point this to be merged into the iOS13 branch? I plan on making an official release once we can get this merged in.

File: NotificationBanner/Classes/StatusBarNotificationBanner.swift [hunk 1]
```diff
@@ -30,13 +30,23 @@ open class StatusBarNotificationBanner: BaseNotificationBanner {
...
-                return 20.0
+                return 20.0 + heightAdjustment
             }
         } set {
             customBannerHeight = newValue
         }
     }
 
+    private var heightAdjustment: CGFloat {
+        // iOS 13 does not allow covering the status bar on non-nothc iPhones
```
Comment (Daltron) [inline NotificationBanner/Classes/StatusBarNotificationBanner.swift]: One small typo here 😄

**Comment by igorkulman** [comment]
I pointed the PR to the `ios13` branch but it is forked from `master` so it contains another fix currentlz in there. Is that OK? Or shall I create a new PR forked from `ios13`  instead?
